"""
Naiba Test Custom Nodes for ComfyUI
包含WAN模型优化、Multi LoRA Loader、Multi LoRA Loader (only model)、Lora Testing Converter和Lora Data Preview功能
"""

from .naiba_wan_blockswap import NODE_CLASS_MAPPINGS as WAN_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as WAN_NODE_DISPLAY_NAME_MAPPINGS
from .multi_lora_loader import NODE_CLASS_MAPPINGS as LORA_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LORA_NODE_DISPLAY_NAME_MAPPINGS
from .multi_lora_loader_only_model import NODE_CLASS_MAPPINGS as LORA_ONLY_MODEL_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LORA_ONLY_MODEL_NODE_DISPLAY_NAME_MAPPINGS
from .visual_lora_loader import NODE_CLASS_MAPPINGS as VISUAL_LORA_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as VISUAL_LORA_NODE_DISPLAY_NAME_MAPPINGS
from .lora_testing_converter import NODE_CLASS_MAPPINGS as CONVERTER_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CONVERTER_NODE_DISPLAY_NAME_MAPPINGS
from .save_text_file import NODE_CLASS_MAPPINGS as SAVE_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SAVE_NODE_DISPLAY_NAME_MAPPINGS
from .lora_data_preview import NODE_CLASS_MAPPINGS as PREVIEW_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as PREVIEW_NODE_DISPLAY_NAME_MAPPINGS

from .custom_data_reader import NODE_CLASS_MAPPINGS as CUSTOM_READER_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CUSTOM_READER_NODE_DISPLAY_NAME_MAPPINGS
from .power_lora_config_reader import NODE_CLASS_MAPPINGS as CONFIG_READER_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CONFIG_READER_NODE_DISPLAY_NAME_MAPPINGS
from .naiba_textbox import NODE_CLASS_MAPPINGS as TEXTBOX_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as TEXTBOX_NODE_DISPLAY_NAME_MAPPINGS
from .civitai_info_reader import NODE_CLASS_MAPPINGS as READER_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as READER_NODE_DISPLAY_NAME_MAPPINGS

from .naiba_tag_picker import NODE_CLASS_MAPPINGS as TAG_PICKER_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as TAG_PICKER_NODE_DISPLAY_NAME_MAPPINGS
from .preset_reader import NODE_CLASS_MAPPINGS as PRESET_READER_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as PRESET_READER_NODE_DISPLAY_NAME_MAPPINGS
from .anima_prompt_node import NODE_CLASS_MAPPINGS as ANIMA_PROMPT_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as ANIMA_PROMPT_NODE_DISPLAY_NAME_MAPPINGS
from .lora_loader_from_preset import NODE_CLASS_MAPPINGS as PRESET_LOADER_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as PRESET_LOADER_NODE_DISPLAY_NAME_MAPPINGS

# 导入预设路由模块（触发路由注册）
from . import preset_routes
from . import naiba_tag_picker
from . import anima_prompt_node

# 合并节点映射
NODE_CLASS_MAPPINGS = {
    **WAN_NODE_CLASS_MAPPINGS,
    **LORA_NODE_CLASS_MAPPINGS,
    **LORA_ONLY_MODEL_NODE_CLASS_MAPPINGS,
    **VISUAL_LORA_NODE_CLASS_MAPPINGS,
    **CONVERTER_NODE_CLASS_MAPPINGS,
    **SAVE_NODE_CLASS_MAPPINGS,
    **PREVIEW_NODE_CLASS_MAPPINGS,

    **CUSTOM_READER_NODE_CLASS_MAPPINGS,
    **CONFIG_READER_NODE_CLASS_MAPPINGS,
    **TEXTBOX_NODE_CLASS_MAPPINGS,
    **READER_NODE_CLASS_MAPPINGS,

    **TAG_PICKER_NODE_CLASS_MAPPINGS,
    **PRESET_READER_NODE_CLASS_MAPPINGS,
    **ANIMA_PROMPT_NODE_CLASS_MAPPINGS,
    **PRESET_LOADER_NODE_CLASS_MAPPINGS,
}
NODE_DISPLAY_NAME_MAPPINGS = {
    **WAN_NODE_DISPLAY_NAME_MAPPINGS,
    **LORA_NODE_DISPLAY_NAME_MAPPINGS,
    **LORA_ONLY_MODEL_NODE_DISPLAY_NAME_MAPPINGS,
    **VISUAL_LORA_NODE_DISPLAY_NAME_MAPPINGS,
    **CONVERTER_NODE_DISPLAY_NAME_MAPPINGS,
    **SAVE_NODE_DISPLAY_NAME_MAPPINGS,
    **PREVIEW_NODE_DISPLAY_NAME_MAPPINGS,

    **CUSTOM_READER_NODE_DISPLAY_NAME_MAPPINGS,
    **CONFIG_READER_NODE_DISPLAY_NAME_MAPPINGS,
    **TEXTBOX_NODE_DISPLAY_NAME_MAPPINGS,
    **READER_NODE_DISPLAY_NAME_MAPPINGS,

    **TAG_PICKER_NODE_DISPLAY_NAME_MAPPINGS,
    **PRESET_READER_NODE_DISPLAY_NAME_MAPPINGS,
    **ANIMA_PROMPT_NODE_DISPLAY_NAME_MAPPINGS,
    **PRESET_LOADER_NODE_DISPLAY_NAME_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]

# ========== 前端JS扩展目录 ==========
# 告诉ComfyUI从此目录加载前端JS扩展
WEB_DIRECTORY = "js"
